version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-ml-workshop"
s3_prefix = "serverless-ml-workshop"
image_repository = "xxxxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/serverless-ml"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_bucket = ""
