AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for untitled

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  WineClassifierFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      # ImageConfig:
        # Uncomment this to override command here from the Dockerfile
        # Command: ["app.lambda_handler"]
      Events:
        WineClassifier:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /classify
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./service
      DockerTag: python3.8-v1

  ModelBucket:
    Type: AWS::S3::Bucket

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WineClassifierApi:
    Description: "API Gateway endpoint URL for Prod stage for WineClassifier function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classify/"
  WineClassifierFunction:
    Description: "WineClassifier Lambda Function ARN"
    Value: !GetAtt WineClassifierFunction.Arn
  WineClassifierFunctionIamRole:
    Description: "Implicit IAM Role created for WineClassifier function"
    Value: !GetAtt WineClassifierFunctionRole.Arn

